### ISSUE TITLE
New database?

### ISSUE THREAD

**Issue by hoorna** [linuxserver/docker-speedtest-tracker#1]
Do we have to create a new database or can we use the same database created for and maintained by the Speedtest docker container https://github.com/alexjustesen/speedtest-tracker?

**Comment by thespad** [comment]
I'm working with the dev to make sure that everything is a drop-in replacement when it goes live, though right now I've not tested an existing sqlite database (postgres will work assuming you provide the same details).

**Comment by hoorna** [comment]
In that case with this beta-release I best can create an temporarily database.
