### ISSUE TITLE
[FEAT] Upgrading to PHP 8.3

### ISSUE THREAD

**Issue by alexjustesen** [linuxserver/docker-speedtest-tracker#11]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I've upgraded the development image to PHP 8.3 (https://github.com/alexjustesen/speedtest-tracker/pull/1385), looking to make the same change for the LSIO image.

### Reason for change

Upgrading to the most current version of PHP.

**Comment by aptalca** [comment]
Just to confirm, `v0.18.7` is compatible with php 8.3, right? Because what we'll be building in the PR.

**Comment by alexjustesen** [comment]
> Just to confirm, `v0.18.7` is compatible with php 8.3, right? Because that's what we'll be building in the PR.

`v0.19.0` incoming which includes compatibility tested code.

**Comment by alexjustesen** [comment]
https://github.com/alexjustesen/speedtest-tracker/releases/tag/v0.19.0 tagged and ready to roll on your schedule 👍

**Comment by aptalca** [comment]
PR opened. I locally built with `v0.18.7` and spun up a fresh sqlite instance, didn't see any issues or errors. I'll try the `v.019.0` tag just to make sure

**Comment by aptalca** [comment]
yup, local build of `v0.19.0` also seems to be good with the rebase

**Comment by alexjustesen** [comment]
Awesome thank you! This reminds me I need to update my pipeline to use the LSIO base during testing so I can catch build errors before they hit your pipeline.

**Comment by aptalca** [comment]
Sounds good. Just waiting for a review from a team member and then we'll be good to merge and push
