### ISSUE TITLE
[FEAT] Support for MAIL_* environment variables

### ISSUE THREAD

**Issue by armond-avanes** [linuxserver/docker-speedtest-tracker#13]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

From what I see in the documentation, there isn't any support for MAIL_* environment variables to setup email notifications:
```
MAIL_MAILER=...
MAIL_HOST=...
MAIL_PORT=...
MAIL_USERNAME=...
MAIL_PASSWORD=...
MAIL_ENCRYPTION=...
MAIL_FROM_ADDRESS=...
MAIL_FROM_NAME=...
```

Is there any plan to add this support?

### Reason for change

I would like to automate the installation and the configuration as much as possible, with little to no need to make any changes through the UI after installation.

**Comment by thespad** [comment]
We pass through any environment variables to the app so if it's a supported environment variable it should work, though I haven't tested the MAIL envs specifically.
