### ISSUE TITLE
[FEAT] Docker image for application CI pipeline

### ISSUE THREAD

**Issue by alexjustesen** [linuxserver/docker-speedtest-tracker#18]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I'd like to build into my CI pipeline building and running the application's test suite within the lsio image to ensure a couple of things:

1. The application builds successfully within the image
2. The test suite successfully passes

Looking for assistance creating that CI workflow.

### Reason for change

This would help me get in front of any issues from the application that might crop up later down the path in your build steps.

**Comment by thespad** [comment]
Do you just want to do it on releases, or tags, commits, etc? We could do a dev tag that built on whatever criteria you need and then you can ingest that into your tests; *or* if they're tests you want to run inside the container we can have an init step that only runs if given envs are set and poke it into our existing CI smoke tests.

Really depends on exactly what you need out of it.
