### ISSUE TITLE
Errors when pulling the image

### ISSUE THREAD

**Issue by hoorna** [linuxserver/docker-speedtest-tracker#2]
I tried to pull the beta image and to build the container, but immediately after I issued the docker-compose file I got a warning and an error (see the two screenshots added). For pulling the image I used the following command in my docker-compose file: "image: lscr.io/linuxserver/speedtest-tracker:latest".

![Schermafbeelding 2023-12-05 204441](https://github.com/linuxserver/docker-speedtest-tracker/assets/7532234/129f86eb-0a31-4567-9662-cb60d7dae51c)
![Schermafbeelding 2023-12-05 204508](https://github.com/linuxserver/docker-speedtest-tracker/assets/7532234/5b715786-ca38-4be0-84ed-3928d1ba5417)

**Comment by aptalca** [comment]
Image isn't published yet. There is only a dev image: https://github.com/linuxserver/docker-speedtest-tracker/pkgs/container/lsiodev-speedtest-tracker

**Comment by thespad** [comment]
Nothing has been pushed live so you won't be able to pull that image, if you want to try out the current dev build the image is `ghcr.io/linuxserver/lsiodev-speedtest-tracker:v0.13.4-pkg-none-dev-07b37705b034c0ac4e70e8cf8b0e63c4d9d6884e`,

**Comment by hoorna** [comment]
I followed the README.md in this link: https://github.com/linuxserver/docker-speedtest-tracker/tree/initial. Now I will try first: ghcr.io/linuxserver/lsiodev-speedtest-tracker:v0.13.4-pkg-none-dev-07b37705b034c0ac4e70e8cf8b0e63c4d9d6884e
