### ISSUE TITLE
[FEAT] Allow for a custom Internal Port

### ISSUE THREAD

**Issue by c11umw** [linuxserver/docker-speedtest-tracker#20]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Request to have an environment variable so that we can define the internal container port away from port 80

### Reason for change

I run 2 speedtest instances here
One regular instance for full ISP speed monitoring and a second instance which passes through a VPN container.

The VPN container contains/manages the ports for all the app containarrs that pass through it.
Each app container connects to the VPN with...
 
Docker CLI:
```
--network=container:[myVPN] \
````
Docker-Compose: 
```
networks:
    'container:[myVPN]': {}
```

If another app container also uses back-end port 80 and is connected to the same VPN container then there's a conflict.
Allowing us to define an alternate back-end port will prevent potential container conflicts.

**Comment by Roxedus** [comment]
The needed configuration file for this is in persistent storage, and available for you to change yourself. We will not facilitate a variable for this.
