### ISSUE TITLE
[FEAT] Trim secret when reading from the file

### ISSUE THREAD

**Issue by kuya1284** [linuxserver/docker-speedtest-tracker#23]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

When leveraging `FILE__DB_PASSWORD` to set the password for a database, many people will use something like `vi` to create the file. By default, `vi` will save files with a trailing new line character. The new line character will prevent authentication to the database from succeeding. It would be nice to trim all white-space characters, especially the new line character just like what many Docker images do.

### Reason for change

To ensure a successful connection to a database when leveraging `FILE__DB_PASSWORD`. It isn't always obvious that the new line character is the reason why authentication would fail, which would lead people to think that the `FILE__DB_PASSWORD` is broken. Trimming the white-space/new line character would ensure that the image would behave like many other images.

**Comment by Roxedus** [comment]
We will not alter secrets. We do log when a secret has a trailing newline.

Docker docs mentions the use of printf for this very reason.
