### ISSUE TITLE
[FEAT] Update CSV export to include Public IP address

### ISSUE THREAD

**Issue by plym237** [linuxserver/docker-speedtest-tracker#6]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

It would be useful if the exported results also included the public ip address of the system that ran the speedtest.

### Reason for change

I frequently have speed drops on my internet connection. I have noticed that this often coincides with my public ip address changing. Having the public ip address in the exported CSV results would allow me to see if the speed drops correlate with the ip address change.

**Comment by j0nnymoe** [comment]
You need to report this to the upstream project https://github.com/alexjustesen/speedtest-tracker
